name: Release

on:
  release:
    types: [published]

jobs:
  add-artifacts-to-github-release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Validate release tag matches extension package.json version
        working-directory: apps/debugger-extension
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          PACKAGE_VERSION=$(jq -r .version package.json)
          if [ "$TAG_NAME" != "$PACKAGE_VERSION" ]; then
            echo "Error: Release tag ($TAG_NAME) does not match package.json version ($PACKAGE_VERSION)"
            exit 1
          fi

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Zip extensions
        working-directory: apps/debugger-extension
        run: |
          pnpm zip
          pnpm zip:firefox

      - name: Attach artifacts to github release
        working-directory: apps/debugger-extension/.output
        run: gh release upload ${{github.event.release.tag_name}} *{chrome,firefox}.zip
        env:
          GH_TOKEN: ${{ github.token }}
